name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      # Navigate to the backend folder
      - name: Change Directory to Backend
        run: cd backend

      
      - name: Install Dependencies
        run: |
          cd backend
          npm install

   
      # - name: Run Tests
      #   run: |
      #     cd backend
      #     npm test  # Replace with your test script or remove if not needed

    
      - name: Build Application
        run: |
          cd backend
          npm run build  # Replace with your build script if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          cd backend
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r . $USER@$HOST:/path/to/deploy/backend
          ssh -i private_key.pem $USER@$HOST "cd /path/to/deploy/backend && npm install --production && pm2 restart app"
