name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Navigate to the backend directory and install dependencies
      - name: Navigate to Backend and Install Dependencies
        working-directory: ./mapui/backend
        run: npm install

      # Run tests (optional, if you have tests)
      - name: Run Tests
        working-directory: ./mapui/backend
        run: npm test  # Replace with your test script if applicable

      # Build the application (optional, if needed)
      - name: Build Application
        working-directory: ./mapui/backend
        run: npm run build  # Replace if applicable, otherwise remove this step

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          # Create a private key file from the secret
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Copy the backend folder to the server
          scp -i private_key.pem -r ./mapui/backend $USER@$HOST:~/mapui/backend

          # SSH into the server and navigate to the backend folder for deployment
          ssh -i private_key.pem $USER@$HOST "
            cd ~/mapui/backend &&
            npm install --production &&
            pm2 restart server.js
          "
